### PR TITLE
Guadaltel contribution

### PR DESCRIPTION
**Pull request by albertobucesGdtl**
Changelog:

- Added ConfigProxyDto, DatasourcePayloadDto and OgcWmsPayloadDto constructors with lombok for proper reception of the response from the api of configuration and authorization.
- Including ClientService and ClientServiceImpl classes with the HttpClient singleton.

### CODE REVIEW

**Comment by albertobucesGdtl** [comment]
Changelog:

- Added interceptors for test request with basic authentication
- Added test templates for those that are missing data to run them on.
- Added comments in the incomplete tests indicating the required changes to make them valid tests.

**Comment by albertobucesGdtl** [comment]
Accepted pull request from fjlopez

**Comment by albertobucesGdtl** [comment]
Changelog:

- Updated README with deployment documentation.
- Added folder docker for deployment.
- Added folder docker/docker-nginx-balanced with the example for nginx balancer.

**Comment by fjlopez** [comment]
@albertobucesGdtl Have you reviewed https://github.com/albertobucesGdtl/sitmun-proxy-middleware/pull/4 ?

**Comment by albertobucesGdtl** [comment]
Merged [albertobucesGdtl#4](https://github.com/albertobucesGdtl/sitmun-proxy-middleware/pull/4)
Added error response for jdbc queries and http request.

**Comment by albertobucesGdtl** [comment]
Merged pull request [albertobucesGdtl#5](https://github.com/albertobucesGdtl/sitmun-proxy-middleware/pull/5).
Added error response for some cases.

**Comment by albertobucesGdtl** [comment]
The tests have been updated, removing redundant elements.

**Pull request merged**
